Implement NuBase elements and stop using polymorphism (#15)

diff --git a/repository b/repository
--- a/repository
+++ b/repository
@@ -12,6 +12,7 @@ Main arguments:
 -b|--build-cpp: build the project under a "build" directory. It can be used together with "--clean".
 -p|--build-python: build the python package in development mode (assumes to be within a virtual environment)
 -d|--build-docs: build the documentation (inside docs/build)
+-t|--format: apply the format
 -c|--clean: clean the repository of temporary files, caches, build directories, ...
 -f|--force: when specified before any number of commands described above, forces their execution, without any further interaction with the user
 
@@ -36,8 +37,25 @@ while [[ $# -gt 0 ]]; do
 	    cmake ../ -DINSTALL_TESTS=ON
 	    make -j $[$(($(nproc) - 1)) | 1] install
 	    cd ..
+	    if [ ! $? -eq 0 ]; then
+		echo "ERROR: compilation failed"
+		exit 1
+	    fi
 	    shift
 	    ;;
+	-t|--format)
+
+	    echo "Formatting files"
+	    python setup.py apply_format --regex '(docs|python|include|test|scripts)'
+	    if [ $? -eq 0 ]; then
+		echo "Successfully formatted files"
+	    else
+		echo "ERROR: Failed to format files"
+		exit 1
+	    fi
+	    shift
+	    ;;
+
 	-c|--clean)
 
 	    echo "Running \"make clean\" in the documentation directory"
@@ -90,6 +108,10 @@ while [[ $# -gt 0 ]]; do
 
 	    echo "Build python package"
 	    pip install --force-reinstall -e .
+	    if [ ! $? -eq 0 ]; then
+		echo "ERROR: Unable to install as a python package"
+		exit 1
+	    fi
 	    shift
 	    ;;
 
@@ -99,6 +121,10 @@ while [[ $# -gt 0 ]]; do
 	    cd docs
 	    make html
 	    cd -
+	    if [ ! $? -eq 0 ]; then
+		echo "ERROR: Failed to build the documentation"
+		exit 1
+	    fi
 	    shift
 	    ;;
 
